<a href="https://colab.research.google.com/github/Rachita-G/Python_Practice/blob/main/Tensorflow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors
Tensors are multi-dimensional arrays with a uniform type (called a dtype). You can see all supported dtypes at tf.dtypes.DType.

A tensor represents a (possibly multi-dimensional) array of numerical values. With one axis, a tensor corresponds (in math) to a vector. With two axes, a tensor corresponds to a matrix. Tensors with more than two axes do not have special mathematical names.

`Tensors will become more important when we start working with images, which arrive as  n -dimensional arrays with 3 axes corresponding to the height, width, and a channel axis for stacking the color channels (red, green, and blue). For now, we will skip over higher order tensors and focus on the basics`

Ref: https://d2l.ai/chapter_preliminaries/linear-algebra.html

If you're familiar with NumPy, tensors are (kind of) like np.arrays.
The tensor class is similar to NumPy’s ndarray with a few killer features. 
- First, GPU is well-supported to accelerate the computation whereas NumPy only supports CPU computation. 
- Second, the tensor class supports automatic differentiation. 
These properties make the tensor class suitable for deep learning. 

Note: All tensors are immutable like python numbers and strings: you can never update the contents of a tensor, only create a new one.

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.4.1


## Simple Constants

Let's show how to create a simple constant with Tensorflow, which TF stores as a tensor object:

In [ ]:
hello = tf.constant('Hello World')
hello

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello World'>

In [ ]:
print(hello)

tf.Tensor(b'Hello World', shape=(), dtype=string)


In [ ]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [ ]:
hello.numpy()

b'Hello World'

In [ ]:
x = tf.constant(100)
x

<tf.Tensor: shape=(), dtype=int32, numpy=100>

In [ ]:
# tensors- constant
scalar=tf.constant(4) # vector with no axis
print(scalar)
vector=tf.constant([2.3,3.8]) # vector with 1 axis
print(vector)
matrix=tf.constant([[2,3],[0,7]]) # vector with 2 axis
print(matrix)
matrix3d=tf.constant([   # vector with 3 axis
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])
print(matrix3d)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([2.3 3.8], shape=(2,), dtype=float32)
tf.Tensor(
[[2 3]
 [0 7]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [ ]:
# rank - no of dimensions
print(tf.rank(matrix).numpy())
print(tf.rank(matrix3d).numpy())

2
3


In [ ]:
import numpy as np
numpy_array=np.array(matrix)
tf.constant(numpy_array)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [0, 7]], dtype=int32)>

In [ ]:
scalar.assign(10) # constants can't be changed

AttributeError: ignored

## Variables

In [ ]:
# Tensors-- Variable
string=tf.Variable('this is a string',tf.string)
number=tf.Variable(324,tf.int64)
floating=tf.Variable(22.2,tf.float64)
print(string,'\n',number,'\n',floating)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'> 
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324> 
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=22.2>


In [ ]:
string

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>

In [ ]:
string.numpy()

b'this is a string'

In [ ]:
tf.rank(string) # see numpy --- no dimension-- as it a single scalar value

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [ ]:
var=tf.Variable([[1,2,3],[3,4,5]])
var.numpy()

array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)

In [ ]:
var[0,2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[  1,   2, 100],
       [  3,   4,   5]], dtype=int32)>

In [ ]:
var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[  1,   2, 100],
       [  3,   4,   5]], dtype=int32)>

## Operations

In [ ]:
string=tf.constant('hello rachu')
print(string)
print(tf.strings.length(string))
print(tf.strings.unicode_decode(string,'UTF8'))# decode unto another format- UTF. Used in NLP

tf.Tensor(b'hello rachu', shape=(), dtype=string)
tf.Tensor(11, shape=(), dtype=int32)
tf.Tensor([104 101 108 108 111  32 114  97  99 104 117], shape=(11,), dtype=int32)


In [ ]:
string_array=tf.constant(['ai','ml','stats'])
for st in string_array:
  print(st)

tf.Tensor(b'ai', shape=(), dtype=string)
tf.Tensor(b'ml', shape=(), dtype=string)
tf.Tensor(b'stats', shape=(), dtype=string)


In [ ]:
x = tf.constant([[1,2],[3,2]])
print(x)
print(x+2)
print(x*2)
print(np.square(x))

tf.Tensor(
[[1 2]
 [3 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[3 4]
 [5 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 4]
 [6 4]], shape=(2, 2), dtype=int32)
[[1 4]
 [9 4]]


In [ ]:
x = tf.constant(3)
y = tf.constant(2)
print('x is', x.numpy())
print('y is ',y.numpy())
print('Addition',tf.add(x,y).numpy())
print('Subtraction',tf.subtract(x,y).numpy())
print('Multiplication',tf.multiply(x,y).numpy())
print('Division',tf.divide(x,y).numpy())
print('Mean',tf.reduce_mean([x,y]).numpy())
print('Sum',tf.reduce_sum([x,y]).numpy())
print('Square of x',tf.square(x).numpy())

x is 3
y is  2
Addition 5
Subtraction 1
Multiplication 6
Division 1.5
Mean 2
Sum 5
Square of x 9


In [ ]:
# Operator overloading is also supported
print(tf.square(2) + tf.square(3))

tf.Tensor(13, shape=(), dtype=int32)


In [ ]:
x = tf.constant([1.0, 2, 4, 8])
y = tf.constant([2.0, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # The ** operator is exponentiation

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 3.,  4.,  6., 10.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([-1.,  0.,  2.,  6.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 2.,  4.,  8., 16.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.5, 1. , 2. , 4. ], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 1.,  4., 16., 64.], dtype=float32)>)

In [ ]:
np.dot(x,y) # dot product with tensors

30.0

In [ ]:
tf.exp(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=
array([2.7182817e+00, 7.3890562e+00, 5.4598152e+01, 2.9809580e+03],
      dtype=float32)>

In [ ]:
# Matrix multiplications.
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[5., 6.], [7., 8.]])
print('Matrix 1','\n',matrix1.numpy())
print('\n')
print('Matrix 2','\n',matrix2.numpy())
print('\n')
print('Matrix multiplication','\n',tf.matmul(matrix1, matrix2).numpy())
print('\n')
print('Shape','\n',tf.matmul(matrix1, matrix2).shape)
print('\n')
print('Data Type','\n',tf.matmul(matrix1, matrix2).dtype)

Matrix 1 
 [[1. 2.]
 [3. 4.]]


Matrix 2 
 [[5. 6.]
 [7. 8.]]


Matrix multiplication 
 [[19. 22.]
 [43. 50.]]


Shape 
 (2, 2)


Data Type 
 <dtype: 'float32'>


In [ ]:
# operations

a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 2],
                 [1, 2]]) # Could have also said `tf.ones([2,2])`

print(a.numpy(), "\n")
print(b.numpy(), "\n")
print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n") # elt wise
print(tf.matmul(a, b), "\n") # matrix multiplication
print(tf.transpose(a))

[[1 2]
 [3 4]] 

[[1 2]
 [1 2]] 

tf.Tensor(
[[2 4]
 [4 6]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 4]
 [3 8]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 3  6]
 [ 7 14]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


In [ ]:
# or

print(a + b, "\n") # element-wise addition
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication

tf.Tensor(
[[2 4]
 [4 6]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 4]
 [3 8]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 3  6]
 [ 7 14]], shape=(2, 2), dtype=int32) 



In [ ]:
c = tf.constant([[4,5], [5,4]])
c==tf.transpose(c) # for symmetric matrix

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

In [ ]:
a,tf.reduce_mean(a), tf.reduce_sum(a) / tf.size(a).numpy()

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=float64, numpy=2.5>)

In [ ]:
a,tf.reduce_sum(a,axis=1),tf.reduce_sum(a,axis=1,keepdims=True)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 7])>,
 <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[3],
        [7]])>)

In [ ]:
a/tf.reduce_sum(a,axis=1)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.33333333, 0.28571429],
       [1.        , 0.57142857]])>

In [ ]:
a/tf.reduce_sum(a,axis=1,keepdims=True)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.33333333, 0.66666667],
       [0.42857143, 0.57142857]])>

In [ ]:
a,tf.cumsum(a,axis=0)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [4, 6]])>)

In [ ]:
a,tf.cumsum(a,axis=1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 3],
        [3, 7]])>)

In [ ]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
print(tf.reduce_max(c))
# Find the index of the largest value
print(tf.argmax(c))
# Compute the softmax (computes softmax activation function-- see Activation function file)
print(tf.nn.softmax(c))
# equivalent to,
print(tf.exp(c)/tf.reduce_sum(tf.exp(c)))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2.4558145e-03 6.6755963e-03]
 [9.9074626e-01 1.2226781e-04]], shape=(2, 2), dtype=float32)


## Dot product in tensorflow

one of the most fundamental operations is the dot product. Given two vectors  x,y∈Rd , their dot product  x⊤y  (or  ⟨x,y⟩) is a sum over the products of the elements at the same position:  $x^⊤y=\sum_{i=1}^dx_iy_i $.

In [ ]:
a,b,tf.tensordot(a,b,axes=1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [1, 2]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 3,  6],
        [ 7, 14]], dtype=int32)>)

Note that we can express the dot product of two vectors equivalently by performing an elementwise multiplication and then a sum:

In [ ]:
x=tf.range(4,8)
y=tf.ones(4,dtype=tf.int32)
x,y,tf.reduce_sum(x*y),tf.tensordot(x,y,axes=1)

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 5, 6, 7], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 1, 1, 1], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=22>,
 <tf.Tensor: shape=(), dtype=int32, numpy=22>)

Dot products are useful in a wide range of contexts. For example, given some set of values, denoted by a vector  x∈Rd  and a set of weights denoted by  $w∈R^d$ , the weighted sum of the values in  x  according to the weights  w  could be expressed as the dot product  x⊤w . When the weights are non-negative and sum to one (i.e.,  $(\sum_{i=1}^d wi=1)$ ), the dot product expresses a weighted average. After normalizing two vectors to have the unit length, the dot products express the cosine of the angle between them.

## Matrix Vector product

In [ ]:
x=tf.range(20,60,20)
x,a

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([20, 40])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>)

In [ ]:
tf.linalg.matvec(a,x)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([100, 220])>

In [ ]:
np.dot(a,x),tf.tensordot(a,x,axes=1)

(array([100, 220]),
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([100, 220])>)

## Norms
Some of the most useful operators in linear algebra are norms. Informally, the norm of a vector tells us how big a vector is. The notion of size under consideration here concerns not dimensionality but rather the magnitude of the components.

The  **L2  norm** of  x  is the square root of the sum of the squares of the vector elements:
$ \|\mathbf{x}\|_2 = \sqrt{\sum_{i=1}^n x_i^2} $
where the subscript  2  is often omitted in  L2  norms, i.e.,  ∥x∥  is equivalent to  $∥x∥_2$ .

In [ ]:
u=tf.constant([3.0,4.0])
u,tf.norm(u)

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 4.], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=5.0>)

In deep learning, we work more often with the squared  L2  norm. You will also frequently encounter the  **L1  norm**, which is expressed as the sum of the absolute values of the vector elements: $ \|\mathbf{x}\|_1 = \sum_{i=1}^n \left|x_i \right|.$
As compared with the  L2  norm, it is less influenced by outliers. To calculate the  L1  norm, we compose the absolute value function with a sum over the elements.

In [ ]:
v=tf.constant([-2,4,-5])
v,tf.reduce_sum(tf.abs(v))

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-2,  4, -5])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=11>)

Both the  L2  norm and the  L1  norm are special cases of the more general  Lp  norm: $ \|\mathbf{x}\|_p = \left(\sum_{i=1}^n \left|x_i \right|^p \right)^{1/p}.$ Analogous to  L2  norms of vectors, the Frobenius norm of a matrix  X∈Rm×n  is the square root of the sum of the squares of the matrix elements: $ \|\mathbf{X}\|_F = \sqrt{\sum_{i=1}^m \sum_{j=1}^n x_{ij}^2}.$

The **Frobenius norm** satisfies all the properties of vector norms. It behaves as if it were an  L2  norm of a matrix-shaped vector. Invoking the following function will calculate the Frobenius norm of a matrix.

In [ ]:
tf.ones((4, 9))

<tf.Tensor: shape=(4, 9), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.norm(_) # np.sqrt(9*4)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

## Running Sessions

Now you can create a TensorFlow Session, which is a class for running TensorFlow operations.

A `Session` object encapsulates the environment in which `Operation`
objects are executed, and `Tensor` objects are evaluated. 

Ref: https://www.tensorflow.org/api_docs/python/tf/compat/v1/Session

In [ ]:
with tf.compat.v1.Session() as sess:
    x=tf.constant(3)
    y=tf.constant(6)
    print('Operations with Constants')
    print('Addition',sess.run(x+y))
    print('Subtraction',sess.run(x-y))
    print('Multiplication',sess.run(x*y))
    print('Division',sess.run(x/y))

Operations with Constants
Addition 9
Subtraction -3
Multiplication 18
Division 0.5


In [ ]:
tf.compat.v1.disable_eager_execution()
sess =  tf.compat.v1.Session()
sess

In [ ]:
sess.run(x)

3

In [ ]:
type(sess.run(x))

numpy.int32

## About shapes
Tensors have shapes. Some vocabulary:

* Shape: The length (number of elements) of each of the dimensions of a tensor.
* Rank: Number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.
* Axis or Dimension: A particular dimension of a tensor.
* Size: The total number of items in the tensor, the product shape vector

In [ ]:
#rank or degree of tensors- the number of dimensions involved in tensor
l1=tf.Variable(["hi","you"],tf.string)
l1

<tf.Variable 'Variable:0' shape=(2,) dtype=string, numpy=array([b'hi', b'you'], dtype=object)>

In [ ]:
tf.rank(l1) # numpy gives dimension -- means 1 dimensional

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
l1.shape

TensorShape([2])

In [ ]:
l2=tf.Variable([[3,2],[9,8],[0,2]],tf.int64) # like a matrix--note that no of elts in each subloist should be the same
tf.rank(l2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
l2.shape # gives dimension

TensorShape([3, 2])

In [ ]:
a=tf.ones([3,2,4,5])
print('Tensor:',a)
print("Type of every element:", a.dtype)
print("Number of dimensions:", a.ndim)
print("Shape of tensor:", a.shape)
print("Elements along axis 0 of tensor:",a.shape[0])
print("Elements along the last axis of tensor:", a.shape[-1])
print("Total number of elements: ", tf.size(a).numpy())

Tensor: tf.Tensor(
[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]], shape=(3, 2, 4, 5), dtype=float32)
Type of every element: <dtype: 'float32'>
Number of dimensions: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements:  120


![image.png](attachment:image.png)

## Vector
 we can use a range to create a row vector x containing the first 12 integers starting with 0, though they are created as floats by default. Each of the values in a tensor is called an element of the tensor. 

In [ ]:
x=tf.range(12)
x.shape

TensorShape([12])

If we just want to know the total number of elements in a tensor, i.e., the product of all of the shape elements, we can inspect its size. Because we are dealing with a vector here, the single element of its shape is identical to its size.

In [ ]:
tf.size(x)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [ ]:
# reshape
tf.reshape(x,(3,4)) #prodcut of rows and columns should be equal to the size

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

Reshaping by manually specifying every dimension is unnecessary. If our target shape is a matrix with shape (height, width), then after we know the width, the height is given implicitly. Why should we have to perform the division ourselves? In the example above, to get a matrix with 3 rows, we specified both that it should have 3 rows and 4 columns. Fortunately, tensors can automatically work out one dimension given the rest. We invoke this capability by placing -1 for the dimension that we would like tensors to automatically infer. In our case, instead of calling x.reshape(3, 4), we could have equivalently called x.reshape(-1, 4) or x.reshape(3, -1).

Typically, we will want our matrices initialized either with zeros, ones, some other constants, or numbers randomly sampled from a specific distribution.

In [ ]:
tf.ones((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [ ]:
tf.zeros((1,2,2))

<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.]]], dtype=float32)>

Often, we want to randomly sample the values for each element in a tensor from some probability distribution. For example, when we construct arrays to serve as parameters in a neural network, we will typically initialize their values randomly. The following snippet creates a tensor with shape (3, 4). Each of its elements is randomly sampled from a standard Gaussian (normal) distribution with a mean of 0 and a standard deviation of 1.

In [ ]:
tf.random.normal(shape=[3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.328894  ,  0.6729848 , -0.00293487,  1.3718196 ],
       [-0.18719399,  0.07257051, -0.44557896,  0.16058448],
       [-0.046512  , -0.8543657 , -1.5580683 , -0.41135606]],
      dtype=float32)>

### Reshaping a tensor is of great utility.

The `tf.reshape` operation is fast and cheap as the underlying data does not need to be duplicated.

In [ ]:
# changing the shape
t1=tf.ones([1,2,3]) # creates 1 matrix full of ones with shape of 2,3
t1

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [ ]:
tf.reshape(t1,[2,3,1])

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [ ]:
tf.reshape(t1,[3,-1]) 
# 3 means 3 lists and -1 tells tensor to calculate the size of dimension in that place to fill all the values

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
t=tf.zeros([5,5,5,5])
t

<tf.Tensor: shape=(5, 5, 5, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

  

In [ ]:
tf.reshape(t,[125,-1]) #takes[125,5]

<tf.Tensor: shape=(125, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0.

# Concatenating multiple tensors

We can also concatenate multiple tensors together, stacking them end-to-end to form a larger tensor. We just need to provide a list of tensors and tell the system along which axis to concatenate. 

In [ ]:
x = tf.reshape(tf.range(12, dtype=tf.float32), (3, 4))
y = tf.constant([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(x)
print(y)
tf.concat([x, y], axis=0), tf.concat([x, y], axis=1)

tf.Tensor(
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]], shape=(3, 4), dtype=float32)


(<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 8), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]], dtype=float32)>)

Sometimes, we want to construct a binary tensor via logical statements. Take x == y as an example. For each position, if x and y are equal at that position, the corresponding entry in the new tensor takes a value of 1, meaning that the logical statement x == y is true at that position; otherwise that position takes 0.

In [ ]:
x==y

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])>

In [ ]:
# Summing all the elements in the tensor yields a tensor with only one element
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=float32, numpy=66.0>

### Placeholder

You may not always have the constants right away, and you may be waiting for a constant to appear after a cycle of operations. **tf.placeholder** is a tool for this. It inserts a placeholder for a tensor that will be always fed.

**Important**: This tensor will produce an error if evaluated. Its value must be fed using the `feed_dict` optional argument to `Session.run()`,
`Tensor.eval()`, or `Operation.run()`. For example, for a placeholder of a matrix of floating point numbers:

    x = tf.placeholder(tf.float32, shape=(1024, 1024))

Here is an example for integer placeholders:

In [ ]:
x = tf.compat.v1.placeholder(tf.int32)
y = tf.compat.v1.placeholder(tf.int32)
x,y

(<tf.Tensor 'Placeholder_4:0' shape=<unknown> dtype=int32>,
 <tf.Tensor 'Placeholder_5:0' shape=<unknown> dtype=int32>)

In [ ]:
type(x),type(y)

(tensorflow.python.framework.ops.Tensor,
 tensorflow.python.framework.ops.Tensor)

In [ ]:
## Running operations with variable input
d = {x:20,y:30}
add=tf.add(x,y)
sub=tf.subtract(x,y)
mul=tf.multiply(x,y)
with tf.compat.v1.Session() as sess:
    print('Operations with Constants')
    print('Addition',sess.run(add,feed_dict=d))
    print('Subtraction',sess.run(sub,feed_dict=d))
    print('Multiplication',sess.run(mul,feed_dict=d))

Operations with Constants
Addition 50
Subtraction -10
Multiplication 600


## Broadcasting Mechanism

Previously, we saw how to perform elementwise operations on two tensors of the same shape. 

Under certain conditions, even when shapes differ, we can still perform elementwise operations by invoking the broadcasting mechanism. This mechanism works in the following way: First, expand one or both arrays by copying elements appropriately so that after this transformation, the two tensors have the same shape. Second, carry out the elementwise operations on the resulting arrays.

In [ ]:
a = tf.reshape(tf.range(3), (3, 1))
b = tf.reshape(tf.range(2), (1, 2))
a, b

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]])>, <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]])>)

In [ ]:
a+b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]])>

In [ ]:
# broadcasting
import numpy as np
a=np.array([[1,2,3],[4,5,6]]) # matrix
cal=a.sum(axis=0)
a,cal

(array([[1, 2, 3],
        [4, 5, 6]]), array([5, 7, 9]))

In [ ]:
100*a/cal # percentage

array([[20.        , 28.57142857, 33.33333333],
       [80.        , 71.42857143, 66.66666667]])

## Indexing and Slicing
Just as in any other Python array, elements in a tensor can be accessed by index.

In [ ]:
x=tf.reshape(tf.range(12),(3,-1))
x

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [ ]:
x[-1],x[1:4] # here, elements become lists

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 8,  9, 10, 11])>,
 <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])>)

In [ ]:
x[-1][-1]

<tf.Tensor: shape=(), dtype=int32, numpy=11>

Tensors in TensorFlow are immutable, and cannot be assigned to. Variables in TensorFlow are mutable containers of state that support assignments. Keep in mind that gradients in TensorFlow do not flow backwards through Variable assignments.

Beyond assigning a value to the entire Variable, we can write elements of a Variable by specifying indices.

In [ ]:
x[1,2].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [ ]:
x_var = tf.Variable(x)
x,x_var

(<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])>,
 <tf.Variable 'Variable:0' shape=(3, 4) dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])>)

In [ ]:
x_var[1, 2].assign(9)
x_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  9,  7],
       [ 8,  9, 10, 11]])>

In [ ]:
x_var[0:2,:].assign(tf.ones(x_var[0:2,:].shape,dtype=tf.int32)*12)
x_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=int32, numpy=
array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [ 8,  9, 10, 11]])>

# Saving Memory
Running operations can cause new memory to be allocated to host results. For example, if we write y = x + y, we will dereference the tensor that y used to point to and instead point y at the newly allocated memory. In the following example, we demonstrate this with Python’s id() function, which gives us the exact address of the referenced object in memory. After running y = y + x, we will find that id(y) points to a different location. That is because Python first evaluates y + x, allocating new memory for the result and then makes y point to this new location in memory.

In [ ]:
y=x_var
x,y

(<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])>,
 <tf.Variable 'Variable:0' shape=(3, 4) dtype=int32, numpy=
 array([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])>)

In [ ]:
before=id(y)
y=y+x
id(y)==before

False

This might be undesirable for two reasons. 
- First, we do not want to run around allocating memory unnecessarily all the time. In machine learning, we might have hundreds of megabytes of parameters and update all of them multiple times per second. Typically, we will want to perform these updates in place. 
- Second, we might point at the same parameters from multiple variables. If we do not update in place, other references will still point to the old memory location, making it possible for parts of our code to inadvertently reference stale parameters.

Variables are mutable containers of state in TensorFlow. They provide a way to store your model parameters. We can assign the result of an operation to a Variable with assign.

In [ ]:
tf.zeros_like(y)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])>

In [ ]:
z=tf.Variable(_)
print('id before is ',id(z))
z.assign(x+y)
print('id after is ',id(z))

id before is  2224328173000
id after is  2224328173000


Even once you store state persistently in a Variable, you may want to reduce your memory usage further by avoiding excess allocations for tensors that are not your model parameters.

Because TensorFlow Tensors are immutable and gradients do not flow through Variable assignments, TensorFlow does not provide an explicit way to run an individual operation in-place.

However, TensorFlow provides the tf.function decorator to wrap computation inside of a TensorFlow graph that gets compiled and optimized before running. This allows TensorFlow to prune unused values, and to re-use prior allocations that are no longer needed. This minimizes the memory overhead of TensorFlow computations.

In [ ]:
@tf.function
def computation(x, y):
    z = tf.zeros_like(y)  # This unused value will be pruned out.
    a = x + y  # Allocations will be re-used when no longer needed.
    b = a + y
    c = b + y
    return c + y

computation(x, y)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[48, 52, 56, 60],
       [64, 68, 72, 76],
       [64, 72, 80, 88]])>

### Note
The base `tf.Tensor` class requires tensors to be "rectangular"---that is, along each axis, every element is the same size. However, there are specialized types of Tensors that can handle different shapes:

* ragged (see RaggedTensor below)
* sparse (see SparseTensor below)

### Ragged Tensor
![image.png](attachment:image.png)

In [ ]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

In [ ]:
ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


In [ ]:
print(ragged_tensor.shape)

(4, None)


### Sparse Tensors
Sometimes, your data is sparse, like a very wide embedding space. TensorFlow supports `tf.sparse.SparseTensor` and related operations to store sparse data efficiently.
![image.png](attachment:image.png)

In [ ]:
# Sparse tensors store values by index in a memory-efficient manner
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")

# We can convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


### String Tensors
`tf.string` is a dtype, which is to say we can represent data as strings (variable-length byte arrays) in tensors.

The strings are atomic and cannot be indexed the way Python strings are. The length of the string is not one of the dimensions of the tensor. See `tf.strings` for functions to manipulate them.

In [ ]:
# Tensors can be strings, too here is a scalar string.
scalar_string_tensor = tf.constant("Gray wolf")
print(scalar_string_tensor)
# We can use split to split a string into a set of tensors
print(tf.strings.split(scalar_string_tensor, sep=" "))

tf.Tensor(b'Gray wolf', shape=(), dtype=string)
tf.Tensor([b'Gray' b'wolf'], shape=(2,), dtype=string)


In [ ]:
# If we have two string tensors of different lengths, this is OK.
tensor_of_strings = tf.constant(["Gray wolf",
                                 "Quick brown fox",
                                 "Lazy dog"])
# Note that the shape is (2,), indicating that it is 2 x unknown.
print(tensor_of_strings)

tf.Tensor([b'Gray wolf' b'Quick brown fox' b'Lazy dog'], shape=(3,), dtype=string)


In [ ]:
# ...but it turns into a `RaggedTensor` if we split up a tensor of strings,
# as each string might be split into a different number of parts.
print(tf.strings.split(tensor_of_strings))
print(tf.strings.split(tensor_of_strings).shape)

<tf.RaggedTensor [[b'Gray', b'wolf'], [b'Quick', b'brown', b'fox'], [b'Lazy', b'dog']]>
(3, None)


![image.png](attachment:image.png)

 ----

## NUMPY AND TENSORS
The most obvious differences between NumPy arrays and tf.Tensors are:

- Tensors can be backed by accelerator memory (like GPU, TPU).
- Tensors are immutable.

###### NumPy Compatibility
Converting between a TensorFlow tf.Tensors and a NumPy ndarray is easy:

- TensorFlow operations automatically convert NumPy ndarrays to Tensors.
- NumPy operations automatically convert Tensors to NumPy ndarrays.

Tensors are explicitly converted to NumPy ndarrays using their `.numpy()` method. These conversions are typically cheap since the array and tf.Tensor share the underlying memory representation, if possible. However, sharing the underlying representation isn't always possible since the tf.Tensor may be hosted in GPU memory while NumPy arrays are always backed by host memory, and the conversion involves a copy from GPU to host memory.

In [ ]:
a = x.numpy()
b = tf.constant(a)
type(a), type(b)

NameError: ignored

In [ ]:
# To convert a size-1 tensor to a Python scalar, we can invoke the item function or Python’s built-in functions.
a = tf.constant([3.5]).numpy()
a, a.item(), float(a), int(a)

NameError: ignored

In [ ]:
import numpy as np

ndarray = np.ones([3, 3])
print(ndarray)

print("TensorFlow operations convert numpy arrays to Tensors automatically")
tensor = tf.multiply(ndarray, 42)
print(tensor)

print("And NumPy operations convert Tensors to numpy arrays automatically")
print(np.add(tensor, 1))

print("The .numpy() method explicitly converts a Tensor to a numpy array")
print(tensor.numpy())

### GPU acceleration
Many TensorFlow operations are accelerated using the GPU for computation. Without any annotations, TensorFlow automatically decides whether to use the GPU or CPU for an operation—copying the tensor between CPU and GPU memory, if necessary. Tensors produced by an operation are typically backed by the memory of the device on which the operation executed

In [ ]:
x = tf.random.uniform([3, 3])

print("Is there a GPU available: "),
print(tf.config.experimental.list_physical_devices("GPU"))

print("Is the Tensor on GPU #0:  "),
print(x.device.endswith('GPU:0'))

## Datasets 
This section uses the tf.data.Dataset API to build a pipeline for feeding data to your model. Create a source dataset using one of the factory functions like Dataset.from_tensors, Dataset.from_tensor_slices.Use the transformations functions like map, batch, and shuffle to apply transformations to dataset records. tf.data.Dataset objects support iteration to loop over records

In [ ]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])
ds_tensors = ds_tensors.map(tf.square).shuffle(2).batch(2)
print('Elements of ds_tensors:')
for x in ds_tensors:
      print(x)

Elements of ds_tensors:
tf.Tensor([1 4], shape=(2,), dtype=int32)
tf.Tensor([ 9 16], shape=(2,), dtype=int32)
tf.Tensor([36 25], shape=(2,), dtype=int32)


## Data Preprocessing

In [ ]:
import pandas as pd
num_rooms=[np.nan,2,4,np.nan]
alley=['pave',np.nan,'pave',np.nan]
price=[12500,30000,14500,70000]
data=pd.DataFrame({'num_rooms':num_rooms,'alley':alley,'price':price})
data

num_rooms alley  price
0        NaN  pave  12500
1        2.0   NaN  30000
2        4.0  pave  14500
3        NaN   NaN  70000

In [ ]:
# missing values
inputs=data.iloc[:,[0,1]]
outputs=data.iloc[:,2]
print(inputs)
print(outputs)

   num_rooms alley
0        NaN  pave
1        2.0   NaN
2        4.0  pave
3        NaN   NaN
0    12500
1    30000
2    14500
3    70000
Name: price, dtype: int64


In [ ]:
# for numerical
inputs = inputs.fillna(inputs.mean())
print(inputs)

   num_rooms alley
0        3.0  pave
1        2.0   NaN
2        4.0  pave
3        3.0   NaN


In [ ]:
# for categories
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   num_rooms  alley_pave  alley_nan
0        3.0           1          0
1        2.0           0          1
2        4.0           1          0
3        3.0           0          1


Now that all the entries in inputs and outputs are numerical, they can be converted to the tensor format. Once data are in this format, they can be further manipulated with those tensor functionalities

In [ ]:
X, y = tf.constant(inputs.values), tf.constant(outputs.values)
X, y

(<tf.Tensor: shape=(4, 3), dtype=float64, numpy=
 array([[3., 1., 0.],
        [2., 0., 1.],
        [4., 1., 0.],
        [3., 0., 1.]])>,
 <tf.Tensor: shape=(4,), dtype=int64, numpy=array([12500, 30000, 14500, 70000], dtype=int64)>)