<a href="https://colab.research.google.com/github/Rachita-G/Python_Practice/blob/main/Packages/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).


# Using NumPy

Once you've installed NumPy you can import it as a library:

In [3]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Introduction to Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [4]:
# Prints many statements at the same time
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [5]:
# Creating an array
np.array([1,2,3])
np.array([1,2,3], dtype = float)
np.array([(1,2),(3,4)])

array([1, 2, 3])

array([1., 2., 3.])

array([[1, 2],
       [3, 4]])

In [26]:
x = np.array([(1,2,3),(3,4,5)])
print(type(x)) 
print(len(x)) # length of the array
print(x.shape)
print(x.ndim) # no of array dimensions - 1d/2d/3d etc.
print(x.size) # no of array elements
print(x.dtype) # dtype of array elements
print(x.astype(float)) # changing the dtype

<class 'numpy.ndarray'>
2
(2, 3)
2
6
int64
[[1. 2. 3.]
 [3. 4. 5.]]


In [43]:
# Data Types - https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
np.int_(9.0), np.float_(8), np.bool_(0), np.complex_(4), np.str_(5), np.unicode_(90)

(9, 8.0, False, (4+0j), '5', '90')

In [18]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [188]:
#To get a copy, need to be explicit
arr_copy = x.copy()
arr_copy

array([[1, 2, 3],
       [3, 4, 5]])

# Initial Placeholders

In [ ]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [ ]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [ ]:
np.ones(3)

array([ 1.,  1.,  1.])

In [ ]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [ ]:
np.full((2,2),7) # fill 7 in 2x2 dimenstional array. called constant array

array([[7, 7],
       [7, 7]])

In [ ]:
np.eye(4) # identity matrix

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.identity(6).ndim # means 2 dimensional

2

In [9]:
np.arange(0,10) # Return evenly spaced values within a given interval.
print('\n')
np.arange(0,10,3) #strt,end,step as parameters

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 3, 6, 9])

In [10]:
np.linspace(0,10,3) #Return evenly spaced numbers over a specified interval.

array([ 0.,  5., 10.])

In [11]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [12]:
np.random.random((2,2)) # Create random number arrays - 2x2 array of random numbers

array([[0.55836482, 0.96681642],
       [0.782343  , 0.3752343 ]])

In [13]:
np.empty((2,2)) # Return a new array of given shape and type, without initializing entries.

array([[0.55836482, 0.96681642],
       [0.782343  , 0.3752343 ]])

In [57]:
np.tile(np.array([0,1,2]),2)
np.tile(np.array([3,4,5]),(2,2))
np.tile(np.array([(0,1),(2,3)]),(2,2))

array([0, 1, 2, 0, 1, 2])

array([[3, 4, 5, 3, 4, 5],
       [3, 4, 5, 3, 4, 5]])

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [0, 1, 0, 1],
       [2, 3, 2, 3]])

In [ ]:
np.empty_like(np.array([1,2,3])) # matrix with same shape as arr

array([4607182418800017408, 4611686018427387904, 4613937818241073152])

# Matrix using array

In [ ]:
l=[[1,2],[3,4]]
l

In [193]:
a=np.array([[1,2],[3,4]])
a # formatted as a matrix

array([[1, 2],
       [3, 4]])

In [195]:
np.linalg.det(a) # determninant

-2.0000000000000004

In [196]:
np.linalg.inv(a) 

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [197]:
np.trace(a) # sum of diagonal elements

5

In [198]:
np.diag(a) # vector consisting of the diagonal elts of a

array([1, 4])

In [199]:
np.diag([1,2]) # when passed list returns a diagonal matrix

array([[1, 0],
       [0, 2]])

In [200]:
np.linalg.eig(a)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [201]:
lam,v=np.linalg.eig(a)
lam[0]*v[:,0]==a@v[:,0]
lam[0]*v[:,0],a@v[:,0] # thus, it can be said it is due to numerivcal precision- thus, needed to be rounded off
np.allclose(lam[0]*v[:,0],a@v[:,0])
np.allclose(v@np.diag(lam),a@v)

array([ True, False])

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

True

True

# Arrays of random values

In [69]:
np.random.randint(1,100) # Return random integers from low (inclusive) to high (exclusive).

33

In [70]:
np.random.randint(1,100,10) # 10 random integer numbers between 1 and 100

array([13, 34, 76, 80, 20, 54, 93, 34, 61, 36])

In [181]:
np.random.choice(10,size=(3,3)) # random matrix of size (3,3) with numbers between 0 and 10

array([[9, 1, 8],
       [6, 5, 1],
       [5, 3, 1]])

In [182]:
np.random.choice(10,size=(3,3),replace=False) # replace is for with and without replacement used in boostrapping

array([[1, 2, 4],
       [5, 0, 7],
       [9, 3, 6]])

In [66]:
# Create an array of the given shape and 
# populate it with random samples from a uniform distribution over [0, 1)
print(np.random.rand(2))
print(np.random.rand(2,3))

[0.95788114 0.84315532]
[[0.44452061 0.95768404 0.88787612]
 [0.11567825 0.11224311 0.61727473]]


In [176]:
std = np.random.randn(2) # Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform
std.view(), std.mean(), std.var() # or np.mean(std), np.var(std), np.std(std)

(array([1.94207537, 1.10024894]), 1.5211621563092799, 0.17716793681637932)

In [68]:
np.random.randn(5,5)

array([[-0.37830033, -0.15656082,  0.0932262 ,  0.90790788, -0.40073914],
       [-0.01542839, -0.27408577,  0.01012698, -0.60336826, -0.277178  ],
       [-0.62235688,  0.57743018, -0.51711569,  1.50658584,  1.04737994],
       [ 2.22864683,  0.69751251,  0.80824587, -0.80695201, -1.15828629],
       [-0.19186089,  0.50278498, -0.78393915, -1.67212217,  0.60674666]])

In [71]:
np.random.normal(size=(3,3)) # random number generation from normal distribution

array([[-0.09031338,  0.23992564, -0.99119996],
       [ 1.40739132,  0.3037085 ,  0.79106482],
       [-0.17497173,  0.14904933, -2.27400657]])

# Array Manipulation

In [ ]:
# Transpose
np.transpose([(1,2),(3,4)])
print('\n')
np.array([(1,2),(3,4)]).T # Another way

array([[1, 3],
       [2, 4]])

array([[1, 3],
       [2, 4]])

In [ ]:
np.array([(1,2),(3,4)]).ravel() # flattens the array

array([1, 2, 3, 4])

In [79]:
np.array([1,2,3,4,5,6]).reshape(2,3) # reshape the array

array([[1, 2, 3],
       [4, 5, 6]])

array([[2, 3],
       [4, 7]])

In [44]:
a = np.array([(1,2),(3,4)])
a.resize(2,3) # returns a new array with different shape
a 
print('\n')
np.insert(a,1,4) # position and number - flattens the array
print('\n')
np.append(a,a) # append items to an array - flattens the array
print('\n')
np.delete(a, [1]) # delete items from an array based on position

array([[1, 2, 3],
       [4, 0, 0]])

array([1, 4, 2, 3, 4, 0, 0])

array([1, 2, 3, 4, 0, 0, 1, 2, 3, 4, 0, 0])

array([1, 3, 4, 0, 0])

In [63]:
a = np.array([(1,2),(3,4)])
b = np.array([(0,7), (8,9)])
np.vstack((a,b)) # or np.row_stack((a,b)), np.concatenate((a,b), axis = 0), np.r_[a,b]
print('\n')
np.hstack((a,b)) # or np.column_stack((a,b)), np.concatenate((a,b), axis = 1), np.c_[a,b]
print('\n')

array([[1, 2],
       [3, 4],
       [0, 7],
       [8, 9]])

array([[1, 2, 0, 7],
       [3, 4, 8, 9]])

In [ ]:
# Splitting Arrays
np.hsplit(np.array([1,2,3]),3)
print('\n')
np.vsplit(np.array([[9,0],[7,6]]),2)

[array([1]), array([2]), array([3])]

[array([[9, 0]]), array([[7, 6]])]

In [72]:
# to find min, max or locations of min and max values in an array
a = np.array([1,3,4,5,8,9])
print(a.min())
print(a.argmax())
print(a.argmin())

1
5
0


In [ ]:
a = np.array([(1,2),(3,4)])
print(a.shape)

(2, 2)


In [ ]:
# other ones
print(np.where([True,False],[1,2],[2,3])) # where condition
print(np.where(np.eye(3)>0,3,2)) # means if condition in 1st arg is true then do 2nd. Otherwise, 3rd
print(np.mean([1,2,3,4])) # statitical methods
print(np.sum([1,2,3,4])) 
print(np.eye(3).any()) # returns True if atleast one is True
print(np.eye(3).all()) # returns True if all are True
print(np.sort(np.array([1,2,5,6,2,1,3,4])))
print(np.unique(np.array([1,2,5,6,2,1,3,4])))

[1 3]
[[3 2 2]
 [2 3 2]
 [2 2 3]]
2.5
10
True
False
[1 1 2 2 3 4 5 6]
[1 2 3 4 5 6]


# Array Mathematics

In [85]:
arr = np.arange(0,10)
arr
arr+arr
arr*3
arr**2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [90]:
1/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ])

In [204]:
arr = np.arange(0,5)
arr2=np.array([1,1,1,1,1])
print(arr+arr2)# array math
print(np.add(arr,arr2)) # another way. similarly- np.subtract(), np.divide(), np.multiply()
print(np.dot(arr,arr2)) # dot product. or arr.dot(arr2) or arr@arr2

[1 2 3 4 5]
[1 2 3 4 5]
10


In [231]:
np.exp(0), np.sqrt(9), np.sin(0), np.cos(0), np.tanh(90), np.log(1), np.max([4,6,2])

(1.0, 3.0, 0.0, 1.0, 1.0, 0.0, 6)

In [169]:
a = np.array([1,2,3])
b = np.array([1,6,3])
a == b # elt wise 
a<2
np.array_equal(a,b)

array([ True, False,  True])

array([ True, False, False])

False

In [107]:
a.view() # view the array
np.copy(a) # soft copy
h = np.copy(a) # deepcopy

array([1, 2, 3])

array([1, 2, 3])

In [110]:
b.view()
b.sort() # sorts the array
b.view()

array([1, 3, 6])

array([1, 3, 6])

In [114]:
c = np.array([(9,8),(8, 10)])
c.view()
c.sort(axis = 0)
c.view()

array([[ 9,  8],
       [ 8, 10]])

array([[ 8,  8],
       [ 9, 10]])

In [186]:
c.sum(), c.std(), c.sum(axis= 0), c.sum(axis = 1)

(35, 0.82915619758885, array([17, 18]), array([16, 19]))

In [184]:
np.mean(c), np.var(c)
print()
np.cov(c, rowvar=False)

(8.75, 0.6875)

array([[0.5, 1. ],
       [1. , 2. ]])

## Dot Product

$$a.b=a^T b=\sum_{d=1}^D a_db_d$$

## Calculating Angle
$$a.b=a^T b=\vert\vert\vec{a}\vert\vert \vert\vert\vec{b}\vert\vert cos(\theta)$$

$$\cos(\theta)=\frac{a^Tb}{\vert\vert\vec{a}\vert\vert \vert\vert\vec{b}\vert\vert}$$

$$\vert\vert\vec{a}\vert\vert=\sqrt{\sum_{d=1}^D a_d^2}$$

In [214]:
a = np.arange(0,5)
b=np.array([1,1,1,1,1])
dot=0
for e,f in zip(a,b):
    dot+=e*f
dot

10

In [216]:
dot=0
for i in range(len(a)):
    dot+=a[i]*b[i]
dot

10

In [215]:
print(np.dot(a,b)) # dot product. or a.dot(b) or a@b

10


In [210]:
magnitude_a=np.sqrt((a*a).sum())
magnitude_a

5.477225575051661

In [211]:
np.linalg.norm(a) # for magnitude

5.477225575051661

In [212]:
cos_angle=a.dot(b)/(np.linalg.norm(a)*np.linalg.norm(b))
cos_angle

0.8164965809277259

In [213]:
angle=np.arccos(cos_angle) # theta
angle # ans is in radians and not in degrees

0.6154797086703875

**Solving a set of linear equations**

$$ a+b=2200 $$
$$ 1.5a+4b=5050 $$
Set them as matrices:
where a=[1 1][1.5 4] b[2200 5050] x=[a b]

Eq: Ax=b => x=A^-1 b

In [191]:
a=np.array([[1,1],[1.5,4]])
b=np.array([2200,5050])
np.linalg.solve(a,b)

array([1500.,  700.])

In [192]:
# donot use- not advised
np.linalg.inv(a).dot(b)

array([1500.,  700.])

# Array Subsetting

In [125]:
arr = np.arange(0,11)
arr[::2]

array([ 0,  2,  4,  6,  8, 10])

In [126]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [129]:
arr = np.arange(0,11)
arr[:] = 99
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [139]:
# Indexing - Slicing
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d
print()
arr_2d[:2,1:]
print()
arr_2d[2,:] # or arr_2d[2]
print()
arr_2d[0,1] # or arr_2d[0][1]
print()
arr_2d[1,...] # same as arr_2d[1,:,:]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

array([[10, 15],
       [25, 30]])

array([35, 40, 45])

10

array([20, 25, 30])

In [142]:
# Boolean Indexing
arr_2d[arr_2d <25] # gives results and flattens the data

array([ 5, 10, 15, 20])

In [166]:
# Fancy indexing
arr1 = np.array([(1,2,3), (3,4,5)])
arr1
arr1[[1,1],[0,1]] # select items of (1,0), (1,1)
arr1[[1,1]]

array([[1, 2, 3],
       [3, 4, 5]])

array([3, 4])

array([[3, 4, 5],
       [3, 4, 5]])

# Numpy VS List

In [224]:
l=[1,2,3]
a=np.array([1,2,3])

In [225]:
[x for x in l]
[y for y in a]

[1, 2, 3]

[1, 2, 3]

In [226]:
l.append(4)
# a.append(4) # gives error

In [227]:
l+[5] # concat - adds element
a+np.array([5]) # broadcasting - adding element wise 5 to each

[1, 2, 3, 4, 5]

array([6, 7, 8])

In [230]:
l*2 # repeats the data twice, l**2 gives error
a*2 # multiplies elt wise, a**2 gives square of elt

[1, 2, 3, 4, 1, 2, 3, 4]

array([2, 4, 6])

## Dot product - Speed test

In [202]:
# vectorisation
import numpy as np
import time as t
a=np.random.rand(1000000)
b=np.random.rand(1000000)
tic=t.time()
c=np.dot(a,b)
toc=t.time()
print(c)
print('vectorisation(using numpy): '+str(1000*(toc-tic))+"ms")

print('\n')

c=0
tic=t.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc=t.time()
print(c)
print("looping(using lists): "+str(1000*(toc-tic))+"ms")

250125.44809702196
vectorisation(using numpy): 1.4905929565429688ms


250125.44809703468
looping(using lists): 488.29030990600586ms


In [203]:
# vectorisation
import numpy as np
import time as t
a=np.array([[1,2],[3,4]])
b=np.array([[1,2,3],[4,5,6]])
tic=t.time()
c=np.dot(a,b)
toc=t.time()
print(c)
print('vectorisation(using numpy): '+str(1000*(toc-tic))+"ms")

print('\n')

c=np.zeros([2,3])
tic=t.time()
for i in range(len(a)):
    for j in range(len(b[1])):
        for k in range(len(b)):
            c[i][j]+=a[i,k]*b[k,j]
toc=t.time()
print(c)
print("looping(using lists): "+str(1000*(toc-tic))+"ms")

[[ 9 12 15]
 [19 26 33]]
vectorisation(using numpy): 0.10251998901367188ms


[[ 9. 12. 15.]
 [19. 26. 33.]]
looping(using lists): 0.13303756713867188ms
